import assert from 'node:assert/strict'
import { DRAFT_TTL_MS, canApplyRestore, canClearDraft, classifyQueueFailure, fingerprintQueueItem, isDraftExpired, nextQueueItem, retryDelay, shouldAutoRetry, shouldPresentTerminal, shouldQueueOnlineFailure, transitionQueueItem, recoverQueueItem, shouldPurgeDraft, validateSchema, selectCanvasOutput, nextSubmission, refreshLease, shouldResumeQueue, shouldUseDirectSubmitFallback } from '../src/lib/offline-waste.ts'

const now = 1_000_000
assert.equal(isDraftExpired({ updatedAt: now - DRAFT_TTL_MS - 1 }, now), true)
assert.equal(isDraftExpired({ updatedAt: now - DRAFT_TTL_MS }, now), false)
assert.equal(shouldPurgeDraft({ updatedAt: now - DRAFT_TTL_MS - 1, schemaVersion: 1 }, now), true)
assert.equal(shouldPurgeDraft({ updatedAt: now, schemaVersion: 2 }, now), false)
assert.equal(validateSchema({ schemaVersion: 1 }), true)
assert.equal(validateSchema({ schemaVersion: 2 }), false)
assert.equal(classifyQueueFailure(409), 'duplicate')
assert.equal(classifyQueueFailure(401), 'auth-required')
assert.equal(classifyQueueFailure(503), 'retryable-failure')
assert.equal(classifyQueueFailure(400), 'manual-failure')
assert.equal(shouldAutoRetry({ state: 'retryable-failure', attempts: 0 }), true)
assert.equal(shouldAutoRetry({ state: 'retryable-failure', attempts: 1 }), true)
assert.equal(shouldAutoRetry({ state: 'retryable-failure', attempts: 2 }), true)
assert.equal(shouldAutoRetry({ state: 'retryable-failure', attempts: 3 }), false)
assert.equal(shouldQueueOnlineFailure(503), true)
assert.equal(shouldQueueOnlineFailure(400), false)
assert.equal(shouldUseDirectSubmitFallback(false), true)
assert.equal(shouldUseDirectSubmitFallback(true), false)
assert.equal(shouldResumeQueue({ state: 'auth-required', attempts: 0 }, false), false)
assert.equal(shouldResumeQueue({ state: 'auth-required', attempts: 0 }, true), true)
const queued = [{ id: 'later', state: 'queued' as const, createdAt: 2, attempts: 0 }, { id: 'first', state: 'queued' as const, createdAt: 1, attempts: 0 }, { id: 'manual', state: 'manual-failure' as const, createdAt: 0, attempts: 0 }]
assert.equal(nextQueueItem(queued)?.id, 'first')
assert.deepEqual(transitionQueueItem(queued[1], 'retryable-failure', 'offline'), { ...queued[1], state: 'retryable-failure', attempts: 1, lastError: 'offline' })
assert.deepEqual(recoverQueueItem({ id: 'crashed', state: 'syncing' as const, leaseUntil: now - 1, attempts: 0 }, now), { id: 'crashed', state: 'queued', leaseUntil: undefined, attempts: 0 })
assert.equal(recoverQueueItem({ id: 'live', state: 'syncing' as const, leaseUntil: now + 1, attempts: 0 }, now).state, 'syncing')
assert.equal(refreshLease({ state: 'syncing' as const, leaseUntil: now }, now).leaseUntil > now, true)
assert.deepEqual(selectCanvasOutput('image/webp'), { type: 'image/webp', extension: 'webp' })
assert.deepEqual(selectCanvasOutput(''), { type: 'image/jpeg', extension: 'jpg' })
assert.equal(nextSubmission([{ state: 'completed' }, { state: 'duplicate' }, { state: 'queued' }])?.state, 'queued')
assert.equal(nextSubmission([{ state: 'completed' }, { state: 'duplicate' }]), undefined)
assert.equal(canApplyRestore(0, 0), true)
assert.equal(canApplyRestore(0, 1), false)
assert.equal(retryDelay(1), 250)
assert.equal(retryDelay(3), 750)
assert.equal(shouldPresentTerminal('completed'), true)
assert.equal(shouldPresentTerminal('duplicate'), true)
assert.equal(canClearDraft(4, 4), true)
assert.equal(canClearDraft(4, 5), false)
assert.equal(fingerprintQueueItem({ form: 'manual', businessDate: '2026-08-07', shift: 'OPENING', submissions: [{ payload: { a: 1 } }] }), fingerprintQueueItem({ shift: 'OPENING', submissions: [{ payload: { a: 1 } }], businessDate: '2026-08-07', form: 'manual' }))
console.log('check-offline-waste: PASS')
